<div style="width:250px; height:300px; margin: 0 auto; padding-top: 200px;">
	<div class="container_4 clearfix">
		<!-- Main Section -->
		<section class="main-section grid_4" style="height:auto;">
	
			<div class="main-content" style="min-height:0;">
				<header>
					<h2><?php echo $this->translate('Welcome to CRM'); ?></h2>
				</header>
				<section class="container_4 clearfix">
				<?php if($this->confirm) : ?>
				<div class="message success">
					<?= $this->translate($this->confirm); ?>
				</div>
				<?php endif;?>
					<?php if($this->msg) : ?>
				<div class="message error">
					<?= $this->translate($this->msg); ?>
				</div>
				<?php endif;?>
				<form action="" method="post">
				<?= $this->form->username ?>
				<?= $this->form->password ?>
				<a href="/index/register/"><?php echo $this->translate('Register')?></a>
				<br /><a href=""><?php echo $this->translate('Password Recovery')?></a>
				<?= $this->form->login ?>
				</form>
				<div class="clear"></div>
				</section>
			</div>
		</section>
		<!-- Main Section End -->
	</div>
	<div id="push"></div>
</div>