<!-- Main Section -->

                <section class="main-section grid_7">

                    <div class="main-content grid_5 alpha">
<header>
	<ul class="action-buttons clearfix fr">
	</ul>
	<div class="view-switcher">
		<form style="float:right;" id="filters_form">
			<select id="contact_type">
					<option><?php echo $this->translate('Choose person or company'); ?></option>
					<option  value="1">
						<?php echo $this->translate('Person'); ?>
					</option>
					<option  value="0">
						<?php echo $this->translate('Company'); ?>
					</option>
			</select>
		</form>
		<h2><?php echo $this->translate('All Contacts'); ?></h2>
	</div>
</header>

	<?php if($this->msg) : ?>
	<div style="padding: 5px;">
		<div class="message success">
			<?= $this->translate($this->msg); ?>
		</div>
	</div>
	<?php endif;?>
	<?php if($this->error) : ?>
	<div style="padding: 5px;">
		<div class="message error">
			<?= $this->translate($this->error); ?>
		</div>
	</div>
	<?php endif;?>

<?php
if ($this->allcontacts) :
	?>
	                       <section>
	                       <div class="search_fields">
	                       		<?php if($this->custom){
	                       			foreach($this->custom as $i=>$val)
	                       			{
	                       				echo '	<span class="tag" style="margin: 2px;">
						                       		<a class="search_field" id="'.$val['name'].'">
						                       			'.$val['label'].'
						                       		</a>
					                       		</span>
												<input type="text" class="filter_input" id="'.$val['name'].'" value="" name="'.$val['name'].'" style="display:none" />
												<a  class="button button-gray filter" id="'.$val['name'].'" style="display:none">
													'.$this->translate('Filter').'
												</a>
												<a class="button button-gray cancel" id="'.$val['name'].'" style="display:none">
													'. $this->translate('Cancel').'
												</a>
												';
	                       			}
	                       		}?>
	                       </div>
	                        <ul id="contacts" class="listing list-view clearfix">
                        	<?php
							foreach ( $this->allcontacts as $task ) :
								?>
                           
                              
                              <?php if($task["type"]): ?>  
                                	<li class="contact clearfix">
                                    <div class="avatar"><img src="/images/user_32.png" /></div>
                                    <a href="/contact/personrecord/id/<?php echo $task['id']?>" class="name"><?php echo $task ['name']; ?></a>
                                    <div class="entry-meta">
                                        <a href="/contact/editperson/id/<?= $task['id']?>"><img src="/images/icons/pencil.png" /></a>
					    				<a href="/contact/deleteperson/id/<?= $task['id']?>"><img src="/images/icons/delete.png" /></a>
                                    </div>
                              <?php else :?>
                             	 <li class="company clearfix">
                              		<div class="avatar"><img src="/images/users_business_32.png" /></div>
                                    <a href="/contact/companyrecord/id/<?php echo $task['id']?>" class="name"><?php echo $task ['name']; ?></a>
                                    <div class="entry-meta">
                                        <a href="/contact/editcompany/id/<?= $task['id']?>"><img src="/images/icons/pencil.png" /></a>
					    				<a href="/contact/deletecompany/id/<?= $task['id']?>"><img src="/images/icons/delete.png" /></a>
                                    </div>
                              
                              <?php endif;?>
                                </li>
                              
                              <?php endforeach;?>
                                </ul>
                                <div class="gimmimoar">
	                            	<?php echo $this->translate('More'); ?>
	                            </div>
							</div>
							 <div class="preview-pane grid_1 omega">
		                        <div class="content">
		                        <h3><?php echo $this->translate('Easy in easy out');?></h3>
		                        <hr>
			                    <a href="/contact/import/" class=""><b><?php echo $this->translate('Import');?></b></a>
	                            <?php echo $this->translate('or');?>
	                            <a href="/contact/export/" class=""><b><?php echo $this->translate('Export');?></b></a>
	                           	<?php echo $this->translate(' your contacts.');?>
	                           	
	                           	<h3><?php echo $this->translate('Tags');?></h3>
	                           	<hr>
	                           	<?php if($this->tags):?>
	                           	 <?php foreach ($this->tags as $l=> $tags):?>
	                           	 	<b><?php echo $l; ?></b><br />
	                           	 	
	                           	 	<?php foreach ($tags as $tag ):?>
	                           	 		<span class="tag tag<?php echo $tag['id']; ?>"><a class="tag" href="/contact/sort/tag/<?php echo $tag['id']?>"><?php echo $tag['name']?></a></span>
	                           	 	<?php endforeach;?>
	                           	 	<hr>
	                           	  <?php endforeach;?>
	                           	 <?php endif;?>
	                           	<ul class="profile-info">
	                           	</ul>
			                    </div>
		               		</div>
                </section>
                <!-- Main Section End -->
                
                
<script type="text/javascript">
$(function(){
	var data = new Object();
	var filters = new Object();
	data.count = 6;

		$('select#contact_type').change(function(){
				filters.type = $(this).val();
				data.filters = filters;
				if(filters.type == 1)
				{
					$('li.company').hide();
					$('li.contact').show();
					data.count = $('li.contact').size();
				}else{
					$('li.contact').hide();
					$('li.company').show();
					data.count = $('li.company').size();
				}
				data =  addContacts(data);
		});
	
		$('.gimmimoar').mouseover(
			function(){
				data =  addContacts(data);
			}
		);
	
		$(window).scroll(function() {   
			   if($(window).scrollTop() + $(window).height() > $(document).height() - 10) {
				 data =  addContacts(data);
			   }
		});

		$('a.search_field').click(function(){

			$('a.cancel').hide();
			$('input.filter_input').hide();
			$('span.tag').show();
			$('a.filter').hide();
			
			$(this).parent().hide();
			$(this).parent().next().show();
			$(this).parent().next().next().show();
			$(this).parent().next().next().next().show();
		});

		$('a.filter').click(function(){
			var inputs = $('input.filter_input').serializeArray();
			$.each(inputs, function(ii,input){
				if(input.value)
				{
					filters[input.name] = input.value; 
				}
			});
			$('li.contact').remove();
			$('li.company').remove();
			data.count = 0;
			data.filters = filters;
			data =  addContacts(data);
		});


		$('a.cancel').click(function(){
			$('a.cancel').hide();
			$('input.filter_input').hide();
			$('span.tag').show();
			$('a.filter').hide();

			$('li.contact').remove();
			$('li.company').remove();
			data.count = 0;
			data.filters = new Object();
		});
});





</script>
<?php  else :
	?>
<div class="" style="padding: 5px;">
		<div class="message info">
			<h3><?php
				Echo $this->translate ( 'No Contacts' );
				?></h3>
			<p><?php
				Echo $this->translate ( 'There are no contacts' );
				?></p>
		</div>
</div>
	                   
							 <div class="preview-pane grid_1 omega">
		                        <div class="content">
		                        <h3><?php echo $this->translate('Easy in easy out');?></h3>
		                        <hr>
			                    <a href="/contact/import/" class=""><b><?php echo $this->translate('Import');?></b></a>
	                            <?php echo $this->translate('or');?>
	                            <a href="/contact/export/" class=""><b><?php echo $this->translate('Export');?></b></a>
	                           	<?php echo $this->translate(' your contacts.');?>
	                           	
	                           	<h3><?php echo $this->translate('Tags');?></h3>
	                           	<hr>
	                           	<?php if($this->tags):?>
	                           	 <?php foreach ($this->tags as $l=> $tags):?>
	                           	 	<b><?php echo $l; ?></b><br />
	                           	 	
	                           	 	<?php foreach ($tags as $tag ):?>
	                           	 		<span class="tag tag<?php echo $tag['id']; ?>"><a class="tag" href="/contact/sort/tag/<?php echo $tag['id']?>"><?php echo $tag['name']?></a><a href="#" class="tag_delete" onclick="deleteTag(<?php echo $tag['id']?>)">x</a></span>
	                           	 	<?php endforeach;?>
	                           	 	<hr>
	                           	  <?php endforeach;?>
	                           	 <?php endif;?>
	                           	<ul class="profile-info">
	                           	</ul>
			                    </div>
		               		</div>
                </section>

</section>
<?php endif;
?>


                      